<?php

namespace Agenciafmd\Postal\Resources\Postal\Pages;

use Agenciafmd\Admix\Resources\Concerns\RedirectBack;
use Agenciafmd\Postal\Resources\Postal\PostalResource;
use Filament\Resources\Pages\ListRecords;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\PageRegistration;

class ListPostal extends ListRecords
{
    use RedirectBack;

    protected static string $resource = PostalResource::class;

    protected function getHeaderActions(): array
    {
        return [
            CreateAction::make(),
        ];
    }

    public static function route(string $path): PageRegistration
    {
        return parent::route($path); // TODO: Change the autogenerated stub
    }
}
